{
 "title": "Kubernetes cluster monitoring (via Prometheus)",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "escalabilidade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "memory usage by 1m - escalar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=~\"nginx-deploy-escalar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network trans by total - escala",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"escala\",kubernetes_io_hostname=~\"k8s-node\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network trans pkg total - escala",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=~\"escala\",kubernetes_io_hostname=~\"k8s-node\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu usage 1m - escalar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"nginx-deploy-escalar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network receive by total - escala",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"escala\",kubernetes_io_hostname=~\"k8s-node\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network receive pkg total - escala",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=~\"escala\",kubernetes_io_hostname=~\"k8s-node\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "pod p/ atacar - com ataques", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "fs writes total 1m - pod atacado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{pod=~\"pod-p-atacar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network trans pkg total 1m - pod atacado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{pod=~\"pod-p-atacar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu usage total - pod atacado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"pod-p-atacar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fs reads total 1m - pod atacado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{pod=~\"pod-p-atacar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network receive pkg 1m - pod atacado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{pod=~\"pod-p-atacar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usafe 1m - pod atacado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\"pod-p-atacar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network transmit by total 1m - pod atacado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"pod-p-atacar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network receive by total - pod atacado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"pod-p-atacar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "pod observar - Apenas usuarios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "network pkg transmited 1m - obsevar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{pod=~\"pod-observar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fs reads total 1m - observar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{pod=~\"pod-observar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod memory usage 1m - observar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=\"pod-observar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network receive pkg total 1m - observar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{pod=~\"pod-observar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fs writes total 1m - observar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{pod=~\"pod-observar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu usage 1m - observar",
   "type": "timeseries",
   "description": "pod sem ataque\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"pod-observar\"}[1m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "pod network receive bytes 1m - observar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"pod-observar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network transmit bytes 1m - observar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"pod-observar\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node CPU usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{kubernetes_io_hostname=\"k8s-node\"}[1m]))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  }
 ]
}